import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Some Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const header = (
    <header>
      <div className='text-center bg-slate-800 p-8 my-6 rounded-md'>
        <Link href="/">
          <h1 className='text-3x1 text-white font-bold'>Some Blog</h1>
        </Link>
        <p className='text-slate-300'>{metadata.description}</p>
      </div>
    </header>
  )

  const footer = (
    <header>
      <div className='text-center text-slate-400 border-t border-slate-400 mt-6 py-6'>
        <h1>Developed by</h1>
      </div>
    </header>
  )

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='mx-auto max-w-2xl px-6'>
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  )
}
